services:
  api_service:
    container_name: api_service
    ports:
      - "8081:8080"
    build: 
      context: .
      dockerfile: ./apps/api/Dockerfile
    command: sh -c "uvicorn apps.api.main:app --host 0.0.0.0 --port 8080"
    # command: uv run worker/content.py
    # healthcheck:
    #   test: ["CMD-SHELL", "ps aux | grep 'python worker/content.py' | grep -v grep || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: jobs
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: mypassword
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
  processor_service:
    # container_name: processor_service
    # ports:
    #   - "8000:8000"
    build:
      context: .
      dockerfile: ./apps/processor/Dockerfile
    command: sh -c "uvicorn apps.processor.main:app --host 0.0.0.0 --port 8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: jobs
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    volumes:
      - .:/app
    deploy:
      replicas: 3
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  # Redis Service
  redis:
    # container_name: redis
    image: "redis/redis-stack:edge"
    # restart: always
    ports:
      - 6379:6379
      - 8001:8001
    # command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    # command: ["redis-server", "--notify-keyspace-events", "Ksg"]
    environment:
      REDIS_ARGS: "--bind 0.0.0.0 --notify-keyspace-events Ksg --requirepass mypassword"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network # Attach Redis to the shared network
  #RAbbitMQ service
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASS: 123456
    networks:
      - app-network
  # postgres Service
  postgres:
    container_name: postgres
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    external: true # Make the network available to other Docker Compose files
